# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cti 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "cti"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Seyed Razavi"]
  s.date = "2014-02-28"
  s.description = "A gem for implementing multiple table inheritance in rails 4"
  s.email = "seyed@educationapps.co.uk"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "lib/cti.rb",
    "lib/cti/active_record/acts_as_heir.rb",
    "lib/cti/active_record/acts_as_predecessor.rb",
    "lib/cti/railtie.rb"
  ]
  s.homepage = "http://github.com/seyedrazavi/cti"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A gem for implementing multiple table inheritance in rails 4"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
  end
end

